In [3]:
# NumPy

# Importar la librería
import numpy as np


# CREACIÓN DE ARRAYS

# Crear un array a partir de una lista
arr = np.array([1, 2, 3, 4, 5])
print("Array unidimensional:", arr)

# Crear un array bidimensional (matriz)
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Array bidimensional:\n", matriz)


# PROPIEDADES DEL ARRAY
print("\n Propiedades del array")
print("Dimensiones:", matriz.ndim)
print("Forma:", matriz.shape)
print("Tamaño total:", matriz.size)
print("Tipo de datos:", matriz.dtype)


# FUNCIONES PARA CREAR ARRAYS
print("\n Creación de arrays")

# Array de ceros
ceros = np.zeros((2, 3))
print("Array de ceros:\n", ceros)

# Array de unos
unos = np.ones((3, 3))
print("Array de unos:\n", unos)

# Array con rango
rango = np.arange(0, 10, 2)
print("Array con np.arange():", rango)

# Espaciado lineal
lineal = np.linspace(0, 1, 5)
print("Array con np.linspace():", lineal)



# OPERACIONES CON ARRAYS
print("\n Operaciones básicas")

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Suma:", a + b)
print("Resta:", a - b)
print("Producto elemento a elemento:", a * b)
print("División elemento a elemento:", a / b)

# Operaciones con escalares
print("Multiplicación por escalar:", a * 3)


# INDEXADO Y SLICING
print("\n Indexado y slicing")

arr = np.array([10, 20, 30, 40, 50])
print("Primer elemento:", arr[0])
print("Último elemento:", arr[-1])
print("Segmento del 2º al 4º elemento:", arr[1:4])


# ARRAYS MULTIDIMENSIONALES
print("\n Arrays multidimensionales")

matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Elemento [0,0]:", matriz[0, 0])    # primera fila, primera columna
print("Segunda columna completa:", matriz[:, 1])


# ESTADÍSTICAS Y AGREGACIONES
print("\n Estadística básica")

datos = np.array([10, 20, 30, 40, 50])
print("Media:", np.mean(datos))
print("Desviación estándar:", np.std(datos))
print("Suma:", np.sum(datos))
print("Máximo:", np.max(datos))
print("Mínimo:", np.min(datos))

# RESHAPE Y CONCATENACIÓN
print("\n Reshape y concatenación")

a = np.arange(6)
print("Array original:", a)

b = a.reshape((2, 3))
print("Array con reshape (2x3):\n", b)

# Creamos un array para concatenar
c = np.array([[7, 8, 9]])
concatenado = np.concatenate((b, c), axis=0)
print("Concatenado (añadida fila):\n", concatenado)


# EJERCICIOS PRÁCTICOS
print("\n EJERCICIOS PRÁCTICOS")

# EJERCICIO 1
# Crea un array con los números del 1 al 10 y calcula su media y suma.
print("\nEjercicio 1:")
arr = np.arange(1, 11)
print("Array:", arr)
print("Media:", np.mean(arr))
print("Suma:", np.sum(arr))


# EJERCICIO 2
# Crea una matriz 3x3 con valores del 0 al 8 y calcula la transpuesta.
print("\nEjercicio 2:")
matriz = np.arange(9).reshape(3, 3)
print("Matriz original:\n", matriz)
print("Transpuesta:\n", matriz.T)


# EJERCICIO 3
# Genera un array de 10 valores aleatorios entre 0 y 1.
print("\nEjercicio 3:")
aleatorios = np.random.rand(10)
print("Array aleatorio:", aleatorios)


# EJERCICIO 4
# Crea una matriz identidad de 4x4.
print("\nEjercicio 4:")
identidad = np.eye(4)
print("Matriz identidad:\n", identidad)


# EJERCICIO 5
# Crea una matriz 3x3 con valores aleatorios y encuentra su máximo y mínimo.
print("\nEjercicio 5:")
m = np.random.randint(0, 100, (3, 3))
print("Matriz:\n", m)
print("Máximo:", np.max(m))
print("Mínimo:", np.min(m))

Array unidimensional: [1 2 3 4 5]
Array bidimensional:
 [[1 2 3]
 [4 5 6]]

 Propiedades del array
Dimensiones: 2
Forma: (2, 3)
Tamaño total: 6
Tipo de datos: int64

 Creación de arrays
Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array de unos:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array con np.arange(): [0 2 4 6 8]
Array con np.linspace(): [0.   0.25 0.5  0.75 1.  ]

 Operaciones básicas
Suma: [5 7 9]
Resta: [-3 -3 -3]
Producto elemento a elemento: [ 4 10 18]
División elemento a elemento: [0.25 0.4  0.5 ]
Multiplicación por escalar: [3 6 9]

 Indexado y slicing
Primer elemento: 10
Último elemento: 50
Segmento del 2º al 4º elemento: [20 30 40]

 Arrays multidimensionales
Elemento [0,0]: 1
Segunda columna completa: [2 5]

 Estadística básica
Media: 30.0
Desviación estándar: 14.142135623730951
Suma: 150
Máximo: 50
Mínimo: 10

 Reshape y concatenación
Array original: [0 1 2 3 4 5]
Array con reshape (2x3):
 [[0 1 2]
 [3 4 5]]
Concatenado (añadida fila):
 [[0 1 2]
 [3 4 5]
 [7 8 9]]

 EJERCIC