# 📐 NOTEBOOK 1: Fundamentos de NumPy y Arrays

## 🎯 ¿Qué aprenderás en este notebook?

NumPy es la librería fundamental para trabajar con **datos numéricos** en Python. Es la base de todo el Deep Learning.

En este notebook aprenderás:
1. ✅ Qué es un array y por qué es importante
2. ✅ Crear arrays de diferentes formas
3. ✅ Entender dimensiones y formas (shape)
4. ✅ Realizar operaciones matemáticas con arrays
5. ✅ Indexar y seleccionar datos
6. ✅ Generar datos aleatorios


---

## 📚 ¿Por qué necesitas NumPy para Deep Learning?

Imagina que tienes los siguientes datos de estudiantes:

| Estudiante | Nota Matemáticas | Nota Física | Nota Química |
|------------|------------------|-------------|-------------|
| Ana        | 8.5              | 7.0         | 9.0         |
| Luis       | 6.0              | 8.5         | 7.5         |
| María      | 9.0              | 9.5         | 8.0         |

Con listas normales de Python, calcular el promedio sería tedioso:

```python
# Forma complicada con listas
notas_ana = [8.5, 7.0, 9.0]
promedio_ana = sum(notas_ana) / len(notas_ana)
```

Con NumPy, es mucho más simple:

```python
# Forma simple con NumPy
import numpy as np
notas_ana = np.array([8.5, 7.0, 9.0])
promedio_ana = notas_ana.mean()
```

**NumPy hace que trabajar con números sea rápido y fácil.**

---

## 📦 PASO 1: Importar NumPy

Siempre que uses NumPy, debes importarlo al inicio del notebook.

In [ ]:
# Importar NumPy con el alias 'np' (convención estándar)
import numpy as np

# Verificar la versión instalada
print(f"✅ NumPy versión: {np.__version__}")
print("✅ NumPy importado correctamente")

✅ NumPy versión: 2.0.2
✅ NumPy importado correctamente


---

## 🔢 PASO 2: Crear tu primer array

### 📖 Teoría: ¿Qué es un array?

Un **array** es como una lista de Python, pero optimizada para operaciones matemáticas.

**Diferencias clave:**
- ✅ **Lista Python:** `[1, 2, 3]` → Lenta para operaciones matemáticas
- ✅ **Array NumPy:** `np.array([1, 2, 3])` → Rápido y eficiente

### 🧪 EJEMPLO RESUELTO: Crear arrays básicos

In [ ]:
# Crear un array desde una lista
mi_lista = [1, 2, 3, 4, 5]
mi_array = np.array(mi_lista)

print("Lista Python:", mi_lista)
print("Array NumPy:", mi_array)
print("Tipo de datos:", type(mi_array))

# Crear un array directamente
temperaturas = np.array([20.5, 22.0, 19.8, 23.5])
print("\nTemperaturas de la semana:", temperaturas)

Lista Python: [1, 2, 3, 4, 5]
Array NumPy: [1 2 3 4 5]
Tipo de datos: <class 'numpy.ndarray'>

Temperaturas de la semana: [20.5 22.  19.8 23.5]


### ✍️ AHORA TÚ: Crea tus propios arrays

**Completa el código siguiente:**

In [ ]:
# EJERCICIO 1: Crea un array con las edades de 5 personas
# Ejemplo: [25, 30, 22, 35, 28]
edades = np.array([25, 30, 22, 35, 28])
print("Edades:", edades)

# EJERCICIO 2: Crea un array con los precios de 4 productos
# Ejemplo: [10.5, 25.0, 8.75, 15.20]
precios = np.array([10.5, 25.0, 8.75, 15.20])  # 🔍 np.array()
print("Precios:", precios)

# EJERCICIO 3: Crea un array con las notas de un estudiante
# Ejemplo: [7.5, 8.0, 6.5, 9.0, 7.0]
notas = np.array([7.5, 8.0, 6.5, 9.0, 7.0])
print("Notas:", notas)

Edades: [25 30 22 35 28]
Precios: [10.5  25.    8.75 15.2 ]
Notas: [7.5 8.  6.5 9.  7. ]


---

## 📏 PASO 3: Entender dimensiones y formas (shape)

### 📖 Teoría: Dimensiones de arrays

Los arrays pueden tener diferentes dimensiones:

- **1D (vector):** `[1, 2, 3]` → Una fila de números
- **2D (matriz):** `[[1, 2], [3, 4]]` → Tabla con filas y columnas
- **3D (tensor):** `[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]` → Como un cubo de datos

**En Deep Learning:**
- 1D: Un ejemplo (una frase, una imagen aplanada)
- 2D: Varios ejemplos (dataset completo)
- 3D+: Imágenes, videos, secuencias temporales

### 🧪 EJEMPLO RESUELTO: Explorar formas

In [ ]:
# Array 1D (vector)
vector = np.array([1, 2, 3, 4, 5])
print("Vector 1D:", vector)
print("Forma (shape):", vector.shape)  # (5,) significa 5 elementos
print("Número de dimensiones:", vector.ndim)
print()

# Array 2D (matriz)
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Matriz 2D:")
print(matriz)
print("Forma (shape):", matriz.shape)  # (2, 3) significa 2 filas, 3 columnas
print("Número de dimensiones:", matriz.ndim)
print()

# Array 3D (tensor)
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("Tensor 3D:")
print(tensor)
print("Forma (shape):", tensor.shape)  # (2, 2, 2)
print("Número de dimensiones:", tensor.ndim)

### ✍️ AHORA TÚ: Crea y explora formas

**Completa el código siguiente:**

In [ ]:
# EJERCICIO 4: Crea una matriz 2D con las notas de 3 estudiantes en 4 asignaturas
# Ejemplo:
# Estudiante 1: [7.5, 8.0, 6.5, 9.0]
# Estudiante 2: [6.0, 7.5, 8.5, 7.0]
# Estudiante 3: [9.0, 8.5, 9.5, 8.0]

notas_clase = np.array([
    [7.5, 8.0, 6.5, 9.0],  # Estudiante 1
    [6.0, 7.5, 8.5, 7.0],  # Estudiante 2
    [9.0, 8.5, 9.5, 8.0]   # Estudiante 3
])

print("Notas de la clase:")
print(notas_clase)

# .shape → devuelve (filas, columnas)
print("\nForma (shape):", notas_clase.shape)

# .ndim → devuelve el número de dimensiones (en este caso 2)
print("Número de dimensiones:", notas_clase.ndim)

# f-string con los valores del shape
print(f"\n📊 Tenemos {notas_clase.shape[0]} estudiantes y {notas_clase.shape[1]} asignaturas")

---

## ➕ PASO 4: Operaciones matemáticas con arrays

### 📖 Teoría: Operaciones elemento por elemento

NumPy permite hacer operaciones matemáticas directamente sobre arrays:

```python
# Con listas (tedioso):
precios = [10, 20, 30]
con_iva = [p * 1.21 for p in precios]  # Bucle manual

# Con NumPy (simple):
precios = np.array([10, 20, 30])
con_iva = precios * 1.21  # Operación directa
```

### 🧪 EJEMPLO RESUELTO: Operaciones básicas

In [ ]:
# Crear arrays de ejemplo
precios = np.array([10, 20, 30, 40])
cantidades = np.array([2, 1, 3, 2])

print("Precios:", precios)
print("Cantidades:", cantidades)
print()

# Operaciones aritméticas
print("Precio + 5€:", precios + 5)
print("Precio con 21% IVA:", precios * 1.21)
print("Precio con 50% descuento:", precios * 0.5)
print("Total por producto:", precios * cantidades)
print()

# Operaciones estadísticas
print("💰 Precio promedio:", precios.mean())
print("💰 Precio máximo:", precios.max())
print("💰 Precio mínimo:", precios.min())
print("💰 Suma total:", precios.sum())

### ✍️ AHORA TÚ: Realiza operaciones

**Completa el código siguiente:**

In [ ]:
# EJERCICIO 5: Trabajar con temperaturas
temperaturas_celsius = np.array([20, 25, 18, 22, 30])

print("Temperaturas en Celsius:", temperaturas_celsius)

# Convierte a Fahrenheit: F = C * 9/5 + 32
temperaturas_fahrenheit = temperaturas_celsius * 9/5 + 32  # 🔍 Operación vectorizada
print("Temperaturas en Fahrenheit:", temperaturas_fahrenheit)

# Calcula estadísticas
temp_promedio = temperaturas_celsius.mean()  # 🔍 Media
temp_maxima = temperaturas_celsius.max()     # 🔍 Máximo
temp_minima = temperaturas_celsius.min()     # 🔍 Mínimo

print(f"\n🌡️ Temperatura promedio: {temp_promedio}°C")
print(f"🌡️ Temperatura máxima: {temp_maxima}°C")
print(f"🌡️ Temperatura mínima: {temp_minima}°C")

Temperaturas en Celsius: [20 25 18 22 30]
Temperaturas en Fahrenheit: [68.  77.  64.4 71.6 86. ]

🌡️ Temperatura promedio: 23.0°C
🌡️ Temperatura máxima: 30°C
🌡️ Temperatura mínima: 18°C


In [ ]:
# EJERCICIO 6: Trabajar con notas de estudiantes
notas_estudiante = np.array([7.5, 8.0, 6.5, 9.0, 7.0])

print("Notas originales:", notas_estudiante)

# El profesor decide sumar 0.5 puntos a todas las notas
notas_ajustadas = notas_estudiante + 0.5  # 🔍 Operación vectorizada
print("Notas ajustadas:", notas_ajustadas)

# Calcula el promedio final
promedio_final = notas_ajustadas.mean()  # 🔍 Promedio
print(f"\n📊 Promedio final del estudiante: {promedio_final:.2f}")

# ¿Aprobó todas las asignaturas? (nota >= 5)
aprobo_todas = (notas_ajustadas >= 5).all()  # .all() devuelve True si todas las condiciones son True
print(f"✅ ¿Aprobó todas?: {aprobo_todas}")

Notas originales: [7.5 8.  6.5 9.  7. ]
Notas ajustadas: [8.  8.5 7.  9.5 7.5]

📊 Promedio final del estudiante: 8.10
✅ ¿Aprobó todas?: True


---

## 🔍 PASO 5: Indexación y Slicing (Seleccionar datos)

### 📖 Teoría: Acceder a elementos específicos

Al igual que las listas, puedes acceder a elementos de un array usando índices:

```python
array = np.array([10, 20, 30, 40, 50])
#                  0   1   2   3   4  ← índices

array[0]   # 10 (primer elemento)
array[-1]  # 50 (último elemento)
array[1:3] # [20, 30] (del índice 1 al 2)
```

### 🧪 EJEMPLO RESUELTO: Indexación 1D y 2D

In [ ]:
# Array 1D
ventas = np.array([100, 150, 200, 180, 220])
print("Ventas de la semana:", ventas)
print("Lunes (primer día):", ventas[0])
print("Viernes (último día):", ventas[-1])
print("Lunes a Miércoles:", ventas[0:3])  # Del índice 0 al 2
print("Jueves y Viernes:", ventas[-2:])  # Últimos 2 elementos
print()

# Array 2D (matriz)
notas = np.array([
    [7.5, 8.0, 6.5],  # Estudiante 1
    [6.0, 7.5, 8.5],  # Estudiante 2
    [9.0, 8.5, 9.5]   # Estudiante 3
])

print("Tabla de notas:")
print(notas)
print()

print("Notas del estudiante 1:", notas[0])  # Primera fila
print("Nota del estudiante 2 en la asignatura 3:", notas[1, 2])  # Fila 1, Columna 2
print("Todas las notas de la asignatura 1:", notas[:, 0])  # Todas las filas, columna 0
print("Notas de los dos primeros estudiantes:", notas[0:2])  # Primeras 2 filas

Ventas de la semana: [100 150 200 180 220]
Lunes (primer día): 100
Viernes (último día): 220
Lunes a Miércoles: [100 150 200]
Jueves y Viernes: [180 220]

Tabla de notas:
[[7.5 8.  6.5]
 [6.  7.5 8.5]
 [9.  8.5 9.5]]

Notas del estudiante 1: [7.5 8.  6.5]
Nota del estudiante 2 en la asignatura 3: 8.5
Todas las notas de la asignatura 1: [7.5 6.  9. ]
Notas de los dos primeros estudiantes: [[7.5 8.  6.5]
 [6.  7.5 8.5]]


### ✍️ AHORA TÚ: Practica indexación

**Completa el código siguiente:**

In [ ]:
# EJERCICIO 7: Seleccionar elementos de un array 1D
temperaturas = np.array([18, 20, 22, 25, 23, 19, 21])
print("Temperaturas de la semana:", temperaturas)

# Selecciona la temperatura del primer día (índice 0)
primer_dia = temperaturas[0]
print(f"Temperatura del lunes: {primer_dia}°C")

# Selecciona la temperatura del último día (índice -1)
ultimo_dia = temperaturas[-1]
print(f"Temperatura del domingo: {ultimo_dia}°C")

# Selecciona las temperaturas de los 3 primeros días
primeros_tres_dias = temperaturas[0:3]
print(f"Temperaturas lunes-miércoles: {primeros_tres_dias}")

In [ ]:
# EJERCICIO 8: Seleccionar elementos de un array 2D
productos = np.array([
    [10, 5, 20],   # Producto A: [precio, stock, ventas]
    [15, 8, 15],   # Producto B
    [20, 3, 10]    # Producto C
])

print("Datos de productos [precio, stock, ventas]:")
print(productos)
print()

# Selecciona todos los datos del Producto B (fila 1)
producto_b = productos[1]  # 🔍 Índice 1 = segunda fila
print("Producto B:", producto_b)

# Selecciona el precio del Producto C (fila 2, columna 0)
precio_c = productos[2, 0]  # 🔍 Fila 2, columna 0
print(f"Precio del Producto C: ${precio_c}")

# Selecciona todos los precios (columna 0 de todas las filas)
todos_precios = productos[:, 0]  # 🔍 Todas las filas (:), columna 0
print("Todos los precios:", todos_precios)

# Selecciona todas las ventas (columna 2 de todas las filas)
todas_ventas = productos[:, 2]  # 🔍 Todas las filas (:), columna 2
print("Todas las ventas:", todas_ventas)

---

## 🎲 PASO 6: Generar datos aleatorios

### 📖 Teoría: ¿Por qué datos aleatorios?

En Deep Learning, constantemente necesitas:
- **Inicializar pesos** de una red neuronal (valores aleatorios)
- **Simular datos** para pruebas
- **Dividir datasets** de forma aleatoria

NumPy tiene herramientas para generar números aleatorios de forma eficiente.

### 🧪 EJEMPLO RESUELTO: Generar arrays aleatorios

In [ ]:
# Fijar semilla para reproducibilidad (opcional pero recomendado)
np.random.seed(42)  # Siempre generará los mismos números aleatorios

# Números aleatorios entre 0 y 1
aleatorios_01 = np.random.rand(5)  # 5 números entre 0 y 1
print("Números aleatorios [0, 1):", aleatorios_01)

# Números enteros aleatorios
dados = np.random.randint(1, 7, size=10)  # 10 tiradas de dado (1 a 6)
print("Tiradas de dado:", dados)

# Matriz aleatoria (útil para inicializar redes neuronales)
pesos = np.random.randn(3, 4)  # Matriz 3x4 con distribución normal
print("\nPesos iniciales de una red neuronal (3x4):")
print(pesos)

# Array de unos o ceros
unos = np.ones((2, 3))  # Matriz 2x3 llena de unos
ceros = np.zeros((2, 3))  # Matriz 2x3 llena de ceros
print("\nMatriz de unos:")
print(unos)
print("\nMatriz de ceros:")
print(ceros)

### ✍️ AHORA TÚ: Genera datos aleatorios

**Completa el código siguiente:**

In [ ]:
# EJERCICIO 9: Simular datos de un experimento
np.random.seed(42)

# Genera 10 números aleatorios entre 0 y 1 (simular probabilidades)
probabilidades = np.random.rand(10)
print("Probabilidades simuladas:", probabilidades)

# Genera 20 números enteros aleatorios entre 50 y 100 (simular edades)
edades = np.random.randint(50, 100, size=20)
print(f"\nEdades simuladas: {edades}")
print(f"Edad promedio: {edades.mean():.1f} años")

# Genera una matriz 5x3 de números aleatorios (simular dataset)
dataset_simulado = np.random.randn(5, 3)
print("\nDataset simulado (5 ejemplos, 3 características):")
print(dataset_simulado)

---

## 🎯 MINI-PROYECTO FINAL: Sistema de Calificaciones

Ahora vamos a integrar todo lo aprendido en un proyecto práctico.

### 📋 Contexto:
Eres el profesor de una clase con **5 estudiantes** y **4 asignaturas**.
Debes:
1. Crear una matriz con las notas de todos los estudiantes
2. Calcular el promedio de cada estudiante
3. Calcular el promedio de cada asignatura
4. Identificar al mejor estudiante
5. Aplicar una curva de ajuste (sumar 0.5 puntos a todos)

### ✍️ COMPLETA EL PROYECTO:

In [ ]:
# PASO 1: Crear la matriz de notas (5 estudiantes x 4 asignaturas)
# np.random.seed(42) ya indicado en el enunciado
np.random.seed(42)
notas_clase = np.random.uniform(5.0, 10.0, size=(5, 4))  # (min, max, size=(5,4))

print("📊 NOTAS DE LA CLASE")
print("="*50)
print("Formato: [Mat, Fís, Quím, Biol]\n")
for i, notas in enumerate(notas_clase, 1):
    print(f"Estudiante {i}: {np.round(notas, 2)}")
print()

📊 NOTAS DE LA CLASE
Formato: [Mat, Fís, Quím, Biol]

Estudiante 1: [6.87 9.75 8.66 7.99]
Estudiante 2: [5.78 5.78 5.29 9.33]
Estudiante 3: [8.01 8.54 5.1  9.85]
Estudiante 4: [9.16 6.06 5.91 5.92]
Estudiante 5: [6.52 7.62 7.16 6.46]



In [ ]:
# PASO 2: Calcular el promedio de cada estudiante
# Pista: Debes promediar por filas (axis=1)

promedios_estudiantes = notas_clase.mean(axis=1)  # 🔍 Promedio por filas

print("📈 PROMEDIO POR ESTUDIANTE")
print("="*50)
for i, promedio in enumerate(promedios_estudiantes, 1):
    print(f"Estudiante {i}: {promedio:.2f}")
print()

📈 PROMEDIO POR ESTUDIANTE
Estudiante 1: 8.32
Estudiante 2: 6.55
Estudiante 3: 7.87
Estudiante 4: 6.76
Estudiante 5: 6.94



In [ ]:
# PASO 3: Calcular el promedio de cada asignatura
# Pista: Debes promediar por columnas (axis=0)

promedios_asignaturas = notas_clase.mean(axis=0)  # 🔍 Promedio por columnas

asignaturas = ["Matemáticas", "Física", "Química", "Biología"]

print("📚 PROMEDIO POR ASIGNATURA")
print("="*50)
for asignatura, promedio in zip(asignaturas, promedios_asignaturas):
    print(f"{asignatura}: {promedio:.2f}")
print()

📚 PROMEDIO POR ASIGNATURA
Matemáticas: 7.27
Física: 7.55
Química: 6.42
Biología: 7.91



In [ ]:
# PASO 4: Identificar al mejor estudiante
# Pista: Usa argmax() para encontrar el índice del valor máximo

indice_mejor = promedios_estudiantes.argmax()  # 🔍 Índice del mayor promedio
nota_mejor = promedios_estudiantes[indice_mejor]

print("🏆 MEJOR ESTUDIANTE")
print("="*50)
print(f"Estudiante {indice_mejor + 1} con promedio de {nota_mejor:.2f}")
print()

🏆 MEJOR ESTUDIANTE
Estudiante 1 con promedio de 8.32



In [ ]:
# PASO 5: Aplicar curva de ajuste (sumar 0.5 puntos a todas las notas)
# Pero cuidado: las notas no pueden pasar de 10

notas_ajustadas = notas_clase + 0.5  # 🔍 Sumar 0.5 puntos

# Limitar las notas a máximo 10
notas_ajustadas = np.minimum(notas_ajustadas, 10)  # 🔍 np.minimum limita cada valor

print("✨ NOTAS DESPUÉS DEL AJUSTE (+0.5, máx 10)")
print("="*50)
for i, notas in enumerate(notas_ajustadas, 1):
    print(f"Estudiante {i}: {np.round(notas, 2)}")
print()

# Recalcular promedios
nuevos_promedios = notas_ajustadas.mean(axis=1)
print("📊 NUEVOS PROMEDIOS")
print("="*50)
for i, (antes, despues) in enumerate(zip(promedios_estudiantes, nuevos_promedios), 1):
    mejora = despues - antes
    print(f"Estudiante {i}: {antes:.2f} → {despues:.2f} (+{mejora:.2f})")

✨ NOTAS DESPUÉS DEL AJUSTE (+0.5, máx 10)
Estudiante 1: [ 7.37 10.    9.16  8.49]
Estudiante 2: [6.28 6.28 5.79 9.83]
Estudiante 3: [ 8.51  9.04  5.6  10.  ]
Estudiante 4: [9.66 6.56 6.41 6.42]
Estudiante 5: [7.02 8.12 7.66 6.96]

📊 NUEVOS PROMEDIOS
Estudiante 1: 8.32 → 8.76 (+0.44)
Estudiante 2: 6.55 → 7.05 (+0.50)
Estudiante 3: 7.87 → 8.29 (+0.41)
Estudiante 4: 6.76 → 7.26 (+0.50)
Estudiante 5: 6.94 → 7.44 (+0.50)


---

## 🎓 RESUMEN: ¿Qué has aprendido?

### ✅ Conceptos clave:

| Concepto | Qué es | Ejemplo |
|----------|--------|--------|
| **Array** | Estructura optimizada para números | `np.array([1, 2, 3])` |
| **Shape** | Dimensiones del array | `(5, 4)` = 5 filas, 4 columnas |
| **Indexación** | Acceder a elementos específicos | `array[0]`, `matriz[1, 2]` |
| **Operaciones** | Cálculos sobre todo el array | `array * 2`, `array.mean()` |
| **Aleatorios** | Generar datos de prueba | `np.random.rand(5)` |

### 🧠 Funciones NumPy importantes:

```python
# Crear arrays
np.array([1, 2, 3])        # Desde lista
np.zeros((3, 4))           # Matriz de ceros
np.ones((2, 2))            # Matriz de unos
np.random.rand(5)          # Aleatorios [0, 1)
np.random.randint(1, 10, size=5)  # Enteros aleatorios

# Propiedades
array.shape                # Dimensiones
array.ndim                 # Número de dimensiones
array.size                 # Total de elementos

# Estadísticas
array.mean()               # Promedio
array.max()                # Máximo
array.min()                # Mínimo
array.sum()                # Suma total
array.std()                # Desviación estándar

# Operaciones por eje
matriz.mean(axis=0)        # Promedio por columnas
matriz.mean(axis=1)        # Promedio por filas
```

---

## 🚀 ¿Qué sigue?

En el **Notebook 2** aprenderás:
- 📊 **Pandas**: Trabajar con tablas de datos
- 🔍 Explorar datasets reales
- 📁 Leer archivos CSV
- 🧹 Limpiar y preparar datos

---

## ✅ AUTOEVALUACIÓN

Marca lo que has dominado:

- [ ] Crear arrays con `np.array()`
- [ ] Entender qué es el `.shape` de un array
- [ ] Realizar operaciones matemáticas (suma, multiplicación)
- [ ] Calcular estadísticas (mean, max, min)
- [ ] Seleccionar elementos con indexación `array[i]`
- [ ] Trabajar con matrices 2D `matriz[fila, columna]`
- [ ] Generar datos aleatorios con `np.random`
- [ ] Completar el mini-proyecto de calificaciones

---

## 🎉 ¡FELICIDADES!

Has completado el **Notebook 1: Fundamentos de NumPy**.

NumPy es la base de todo el ecosistema de Data Science y Deep Learning en Python. Lo que has aprendido hoy lo usarás en **todos** los proyectos futuros.

**💪 Sigue practicando y nos vemos en el Notebook 2!**